// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SweetBox.Data;

#nullable disable

namespace SweetBox.Api.Migrations
{
    [DbContext(typeof(SweetBoxContext))]
    [Migration("20260326232423_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PedidoItem", b =>
                {
                    b.Property<int>("IdPedidoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPedidoItem"));

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("IdPedidoItem");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProduto");

                    b.ToTable("PedidoItens");
                });

            modelBuilder.Entity("Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPerfil"));

                    b.Property<string>("NomePerfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPerfil");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Estoque", b =>
                {
                    b.Property<int>("IdEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEstoque"));

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("IdEstoque");

                    b.HasIndex("IdProduto")
                        .IsUnique();

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Pagamento", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPagamento"));

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdPagamento");

                    b.HasIndex("IdPedido")
                        .IsUnique();

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("StatusPedido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SweetBox.Api.Models.PedidoItemParametroBolo", b =>
                {
                    b.Property<int>("IdItemParametro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdItemParametro"));

                    b.Property<int>("IdParametro")
                        .HasColumnType("int");

                    b.Property<int>("IdPedidoItem")
                        .HasColumnType("int");

                    b.Property<string>("ValorEscolhido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdItemParametro");

                    b.HasIndex("IdParametro");

                    b.HasIndex("IdPedidoItem");

                    b.ToTable("PedidoItemParametroBolos");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdEstoque")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdProduto");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SweetBox.Api.Models.ProdutosParametrosBolo", b =>
                {
                    b.Property<int>("IdParametro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdParametro"));

                    b.Property<string>("DescParametro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<float>("Mutiplicador")
                        .HasColumnType("float");

                    b.Property<string>("NomeParametro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoParametro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdParametro");

                    b.HasIndex("IdProduto");

                    b.ToTable("ProdutosParametrosBolos");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PedidoItem", b =>
                {
                    b.HasOne("SweetBox.Api.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SweetBox.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Estoque", b =>
                {
                    b.HasOne("SweetBox.Api.Models.Produto", "Produto")
                        .WithOne("Estoque")
                        .HasForeignKey("SweetBox.Api.Models.Estoque", "IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Pagamento", b =>
                {
                    b.HasOne("SweetBox.Api.Models.Pedido", "Pedido")
                        .WithOne("Pagamento")
                        .HasForeignKey("SweetBox.Api.Models.Pagamento", "IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Pedido", b =>
                {
                    b.HasOne("SweetBox.Api.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SweetBox.Api.Models.PedidoItemParametroBolo", b =>
                {
                    b.HasOne("SweetBox.Api.Models.ProdutosParametrosBolo", "Parametro")
                        .WithMany()
                        .HasForeignKey("IdParametro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PedidoItemParametroBolo_ProdutosParametrosBolo");

                    b.HasOne("PedidoItem", "PedidoItem")
                        .WithMany("PedidoItemParametroBolo")
                        .HasForeignKey("IdPedidoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PedidoItemParametroBolo_PedidoItem");

                    b.Navigation("Parametro");

                    b.Navigation("PedidoItem");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Produto", b =>
                {
                    b.HasOne("SweetBox.Api.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Produto_Categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SweetBox.Api.Models.ProdutosParametrosBolo", b =>
                {
                    b.HasOne("SweetBox.Api.Models.Produto", "Produto")
                        .WithMany("ProdutosParametrosBolo")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PedidoItem", b =>
                {
                    b.Navigation("PedidoItemParametroBolo");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Pedido", b =>
                {
                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Produto", b =>
                {
                    b.Navigation("Estoque");

                    b.Navigation("ProdutosParametrosBolo");
                });

            modelBuilder.Entity("SweetBox.Api.Models.Usuario", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
